### PR TITLE
fix: Supports parsing multiple CIDRs with same mask

### PR DESCRIPTION
**Pull request by mack-branch**
Should fix issue #18 which I was also experiencing when trying to use this library.

Not sure how to add/run tests locally - `make test` just tells me there are no tests. But in the project where I used this, we use busted tests and I was able to test it there. Let me know how I can add & run tests.

### CODE REVIEW

**Comment by membphis** [comment]
missing test case, you can take a look at: https://github.com/api7/lua-resty-ipmatcher/blob/master/t/sanity.t

**Comment by mack-branch** [comment]
@membphis  see my comment - im not sure how to run tests

**Comment by spacewander** [comment]
@mack-branch 
You can refer to https://github.com/api7/lua-resty-radixtree/blob/c5a07983853b0bd6c43ded075438c512a3d6bb51/.travis.yml#L24 for set up the test environment.

Unfortunately, it doesn't pass the test:
```
prove -I. -I../test-nginx/lib -I../test-nginx/inc -r t/
t/sanity.t .. 1/?
#   Failed test 'TEST 2: ipv6 address - response_body - response is expected (repeated req 0, req 0)'
#   at /home/lzx/git/lua-resty-ipmatcher/../test-nginx/lib/Test/Nginx/Socket.pm line 1589.
# @@ -1,5 +1,5 @@
#  true
# -false
# +true
#  true
#  false
#  false

#   Failed test 'TEST 7: match binary ip - response_body - response is expected (repeated req 0, req 0)'
#   at /home/lzx/git/lua-resty-ipmatcher/../test-nginx/lib/Test/Nginx/Socket.pm line 1589.
#          got: 'unexpected result for ::2
# ok
# '
#     expected: 'ok
# '
t/sanity.t .. 20/?
#   Failed test 'TEST 10: match with new_with_value - response_body - response is expected (repeated req 0, req 0)'
#   at /home/lzx/git/lua-resty-ipmatcher/../test-nginx/lib/Test/Nginx/Socket.pm line 1589.
# @@ -4,7 +4,7 @@
#  2
#  false
#  3
# -false
# +3
#  4
#  false
#  false

#   Failed test 'TEST 13: bug fixing: same ipv6 prefix with the same mask - response_body - response is expected (repeated req 0, req 0)'
#   at /home/lzx/git/lua-resty-ipmatcher/../test-nginx/lib/Test/Nginx/Socket.pm line 1589.
# @@ -2,4 +2,4 @@
#  true
#  true
#  true
# -false
# +true

#   Failed test 'TEST 14: bug fixing: ipv4 and ipv6 with the same mask - response_body - response is expected (repeated req 0, req 0)'
#   at /home/lzx/git/lua-resty-ipmatcher/../test-nginx/lib/Test/Nginx/Socket.pm line 1589.
# @@ -3,4 +3,4 @@
#  true
#  true
#  true
# -true
# \ No newline at end of file
# +true
# Looks like you failed 5 tests of 41.
t/sanity.t .. Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/41 subtests

Test Summary Report
-------------------
t/sanity.t (Wstat: 1280 Tests: 41 Failed: 5)
  Failed tests:  5, 19, 28, 37, 40
  Non-zero exit status: 5
```

**Comment by mack-branch** [comment]
actually it looks like #17 fixed this issue, but it hasn't been released. it would be great if a new release could be generated, this is a pretty critical bug.
@membphis @spacewander

**Comment by spacewander** [comment]
Sorry for our oversight! I will draw a new release next Monday.

**Comment by spacewander** [comment]
lua-resty-ipmatcher 0.6.1 is released.

**Pull request closed without merging**
